#!/bin/sh

echo "Install filebeat"
rpm -i filebeat-6.6.2-x86_64.rpm

echo "copying settings"

rm -rf /etc/filebeat/filebeat.yml && cp filebeat/filebeat.yml /etc/filebeat/

#filebeat setup --template -E 'output.elasticsearch.hosts=["172.20.0.2:9200"]'
filebeat modules enable system

echo "================================================================"
service filebeat start
echo "start filebeat service"

sysctl -w vm.max_map_count=262144

docker-compose up --build
